server:
  port: 9999

spring:
  datasource:
    name: local
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/test
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
      naming:
        # 这里由于命名规则的原因, 使用转换下划线的命名策略.
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true

redis:
  basic:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: proton123
  #最大空闲
  max-idle: 20
  #最小空闲
  min-idle: 10
  maxTotal: 50

